<a href="https://colab.research.google.com/github/sathish652003/3317colab/blob/main/exp_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
try:
 tf.executing_eagerly()
 print("TF imported with eager execution!")
except ValueError:
 print("TF already imported with eager execution!")
evens = tf.constant([2, 4, 6, 8, 10, 12], dtype=tf.int32)
print("even:", evens)
ones = tf.ones([6], dtype=tf.int32)
print("ones:", ones)
just_beyond_evens = tf.add(evens, ones)
print("just_beyond_evens:", just_beyond_evens)
twos = tf.constant([2, 2, 2, 2, 2, 2], dtype=tf.int32)
evens_doubled = evens * twos
print("evens_doubled:", evens_doubled)
some_matrix = tf.constant([[1, 2, 3], [4, 5, 6]], dtype=tf.int32)
print(some_matrix)
print("\nvalue of some_matrix is:\n", some_matrix.numpy())

TF imported with eager execution!
even: tf.Tensor([ 2  4  6  8 10 12], shape=(6,), dtype=int32)
ones: tf.Tensor([1 1 1 1 1 1], shape=(6,), dtype=int32)
just_beyond_evens: tf.Tensor([ 3  5  7  9 11 13], shape=(6,), dtype=int32)
evens_doubled: tf.Tensor([ 4  8 12 16 20 24], shape=(6,), dtype=int32)
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)

value of some_matrix is:
 [[1 2 3]
 [4 5 6]]
